bug: able to add isolated event with invalid date for feb due to leap year
AY2223S2-CS2103T-T09-2/tp pull request #172
Opened 2023-04-07 05:43 UTC by gmengqi

solution: check if it leap year and validate the date

2023-04-07 06:07 UTC, clydelhui requested changes
Mostly LGTM! Please do update the checks to make it accurate!

2023-04-07 06:07 UTC, clydelhui commented on src/main/java/seedu/address/logic/parser/ParserUtil.java
> +        boolean isLeapYear = date.getYear() % 4 == 0;
Might want to add a few extra conditions for this:
```
A year may be a leap year if it is evenly divisible by 4. 
Years that are divisible by 100 (century years such as 1900 or 2000) cannot be leap years unless they are also divisible by 400. 
(For this reason, the years 1700, 1800, and 1900 were not leap years, but the years 1600 and 2000 were.)
```
The above was taken from Google

2023-04-07 09:14 UTC, lyndonlim27 commented
<img width="940" alt="image" src="https://user-images.githubusercontent.com/80683209/230581623-ef470828-5cf2-48e9-8e51-42b49bb7868b.png">

Could you also change the example help command for isolated event to a date very far into the future.

2023-04-07 09:24 UTC, lyndonlim27 reviewed
LGTM!

2023-04-08 12:57 UTC, clydelhui approved these changes

2023-04-08 12:57 UTC, merged